package facturas;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class elProveedor extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;
    Operaciones operar = new Operaciones();
   
    
    /**
     * Creates new form elProveedor
     */
    public elProveedor()  {
        initComponents();
        String cabecera[]={"Ruc","Razón Social","Nombre Comercial","Dirección","Teléfono"};
        String datos[][]={};
        modelo=new DefaultTableModel(datos,cabecera);
        jTable1.setModel(modelo);
        jTextField1.setText("");
        jTextField1.requestFocus();
       
        //O se puede hacer esto...
        operar.TablaProveedores("select * from proveedor", modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Eliminar Proveedor ");
        setAutoscrolls(true);

        jLabel1.setText("Ruc:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/set-1/delete.gif"))); // NOI18N
        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/eliminarProveedor.PNG"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(166, 166, 166)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(133, 133, 133)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  /*  private void mostrar() {    
        for (int i = 0; i < modelo.getRowCount(); i++) {        
            modelo.removeRow(i);
            i-=1;
        }
        conectar con=new  conectar();
        Connection reg=con.Conectar();
        Statement st;
        try {
            st = reg.createStatement();
            ResultSet rs=st.executeQuery("select*from proveedor");
            while(rs.next()){
                String f=rs.getString("rucProveedor");
                String a=rs.getString("razProveedor");
                String e=rs.getString("nomcomProveedor");
                String b=rs.getString("dirProveedor");
                String c=rs.getString("telProveedor");
                Object datos[]={f,a,e,b,c};
                modelo.addRow(datos);           
            }       
        }
        catch (SQLException ex) {
            Logger.getLogger(elProveedor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }*/
    
    //<editor-fold desc="Botón Eliminar">
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Realmente quiere borrar el registro?", "Confirme la operación", JOptionPane.YES_NO_OPTION)==JOptionPane.YES_OPTION) {
            conectar con=new  conectar();
            Connection reg=con.Conectar();
            String ruc=jTextField1.getText();
            Statement st;
            try {
                st = reg.createStatement();
                String sql="delete from proveedor where rucProveedor='"+ruc+"'";
                int rs=st.executeUpdate(sql);
                if(rs==1){           
                    JOptionPane.showMessageDialog(null, "Se ha borrado el registro");
                }
                else{              
                    JOptionPane.showMessageDialog(null, "No se pudo borrar el registro.\nEl Ruc ingresado no se encuentra registrado o al menos una Factura depende de él. Elimine primero las facturas.", "Error de eliminación", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
                Logger.getLogger(actUsuario.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(null, "No se pudo borrar el registro.\nEl Ruc ingresado no se encuentra registrado o al menos una Factura depende de él. Elimine primero las facturas.", "Error de eliminación", JOptionPane.ERROR_MESSAGE);
            }
            operar.TablaProveedores("select * from proveedor", modelo);
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
